Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -48,19 +48,42 @@ jobs:
 
   check-doxygen:
     runs-on: ubuntu-latest
-  
     steps:
-      # Paso 1: Clonar el repositorio
-      - name: Checkout repository
-        uses: actions/checkout@v3
-  
-      # Paso 2: Instalar Doxygen
-      - name: Install Doxygen
-        run: sudo apt-get install -y doxygen
-  
-      # Paso 3: Validar comentarios de Doxygen
-      - name: Validate Doxygen Comments
+      - name: "Run doxygen command"
+        shell: bash
         run: |
-          doxygen Doxyfile
-          grep "warning:.*document" doxygen.log || echo "All elements are properly documented"
-        
+          # We only make check, not changes
+          DOX_CONF_FILE=$(pwd)/Doxyfile
+  
+          # Append to DOX_CONF_FILE input source directories, if you have libs, add $(pwd)/lib
+          {
+              cat $DOX_CONF_FILE
+              echo "INPUT" = $(pwd)/src $(pwd)/include
+          } > $DOX_CONF_FILE
+  
+          # Generate documentation
+          # dot -c clears Graphviz configuration, doxygen uses Graphviz for generating graphical representations
+          sudo dot -c
+  
+          ERROR_FILE_FLAG=$(pwd)/dox_errors.txt
+  
+          # create documentation: -s specifies comments of configurations items will be omitted.
+          # pipe stderr to error file
+          DOXYGEN_COMMAND=$(doxygen -s $DOX_CONF_FILE 2> $ERROR_FILE_FLAG)
+  
+          # if error file not empty fail
+          if [ -s $ERROR_FILE_FLAG ]; then
+            echo "Error: There are some files that are not documented correctly"
+            exit 1
+          else
+            echo "All files are documented correctly. Niiiceee"
+            exit 0
+          fi
+  
+      # Upload errors as an artifact, when failed
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: Doxygen errors!!!
+          path: ./dox_errors.txt
+          retention-days: 1
